DUMMY_DATA = [
    {
        "term": "Stomach pain",
        "synonym": ['Stage level 1', 'Lobule i of larsell', 'Mho', 'Kcal', 'Primary upper left canine tooth',
                    'Metastasis stages (tumor staging)', 'Universal designation 13d',
                    'Morphinan-3,6-diol, 7,8-didehydro-4,5-epoxy-17-methyl- (5alpha,6alpha)-, diacetate (ester)',
                    "Dietician's calorie", 'Upper case roman letter a (qualifier value)', 'Ampere (qualifier value)',
                    'Right lower first deciduous molar tooth', 'Universal designation c', 'Lower case pea', 'Tooth a',
                    ],
        

        "parent": ['Gyrus, parahippocampal', 'Temporal lobe structure (body structure)', 'Part of brain',
                   'Gyri, parahippocampal', 'Hippocampal formation', 'Entire hippocampus (body structure)', 
                   'Structure of archicortex (body structure)', 'Lobes, temporal', "Ammon's horn", 'Temporal cortices',
                   'Entire hippocampal gyrus', 'Hippocampus major', 'Temporal regions', 'Formations, hippocampal', 
                   'Hippocampal gyri', 'Gyri, hippocampal', 'Brain parts', 'Region, temporal', 'Ammon horn', 'Horn, ammon', 
                   'Entire parahippocampal gyrus (body structure)', 'Hippocampal gyrus structure', 'Cornu ammonis', 
                   'Brain part', 'Archeocortex', 'Temporal lobe', 'Gyrus hippocampus', 'Hippocampus propers', 
                   'Gyrus parahippocampalis', 'Gyrus, hippocampal', 'Formation, hippocampal', 'Phg', 'Parahippocampal gyri', 
                   'Cortex, temporal', 'Acx', 'Ammons horn', 'Parahippocampal gyrus' ],
        

        "child": ['Entire subiculum hippocampi', 'Entire subiculum hippocampi (body structure)', 'Right subiculum', 
                  'Subiculum hippocampi', 'Left subiculum','S ag &#x7c; red blood cells', 'Primary lower rt first molar', 
                   'S ab &#x7c; bld-ser-plas', 'Entire subiculum hippocampi (body structure)', 'Universal designation s', 
                   'Left subiculum', 'Lrd - primary lower right d tooth', 'Haderup designation 04-', '84 - primary low rt 1st molar', 
                   'Entire subiculum hippocampi', 'Entire deciduous mandibular right first molar tooth', 'Entire deciduous mandibular right first molar tooth (body structure)', 
                   'Lrd - primary lower rt d tooth', 'Primary lower right first molar tooth', 'Universal designation 19d', 
                   'Primary lower right d tooth', 'Right subiculum', 'Iso designation 84', 'Subiculum hippocampi', 
                   '84 - primary lower right first molar tooth'],

        "ae": [],
        "docs": ["doc1", "doc2", "doc1"],
        "type": "event"
    },

    
    {
        "term": "advil",
        "synonym": ['Ar', 'Apex cornus posterioris medullae spinalis', 'Zona spongiosas', 'Abdominal lymph node tumor invasion status a',
                    'Lower case roman letter a', 'Atomic mass unit', 'Stage level 1 (tumor staging)', 'Universal designation 12d',
                    'Blood group antigen rh10', 'A tooth', 'Lamina spinalis i', 'L (qualifier value)', 'Urb - primary upper right b tooth',
                    'Primary upper left first molar tooth', 'Upper case roman letter i (qualifier value)', 'Cortex visual',
                    'Visual area of cortex', 'Lower case roman letter d (qualifier value)', 'Da (qualifier value)', 
                    'Total volume', 'Deciduous maxillary right second molar tooth', 'Tumor staging descriptor a', 'Lower case roman letter i (qualifier value)', 
                    'A - ampere', 'Blood group antigen d (substance)', 'Spinal lamina i', 'Apex of the posterior horn of the spinal cord', 
                    'Lower case letter ell', 'Atto-', 'I ag', 'Haderup designation 05+', '3-d entity', '*volume', 'Upper case roman letter d', 
                    'I-antigen', 'A', 'Lamina marginalis', 'Rexed lamina v', 'Liter', 'U', 'I1 (isbt symbol)', 'Abdominal lymph node tumor invasion status a (tumor staging)',
                    'Lobule i of larsell', 'Roman numeral l (qualifier value)', 'Precentral fissure a', 'Blood group antigen d', 
                    'Day (qualifier value)', 'Lingula of cerebellum (body structure)', 'Ampere', 'Roman numeral l', 'D nos', 
                    'Marginal zone of the spinal cord', 'Lower case roman letter d', 'Lobule v', 'Nucleus, marginal', 'Litre(s)', 'I- element', 
                    'A (tumor staging)', 'D - answer to question', 'Lingula of cerebellum', 'Marginal nucleus', 'Structure of deciduous maxillary right second molar tooth (body structure)',
                    'D day', 'Deciduous mandibular left first molar tooth', 'Lld - primary lower left d tooth', 'Apex cornus dorsalis medullae spinalis', 
                    'A - answer to question', 'Roman numeral i (qualifier value)', 'V (qualifier value)', 'Iodine product', 'Roman numeral upper case eye',
                    'Rh blood group haplotype', 'Stage 1', "Component 'a' of the medial forebrain bundle", 'Amps', 'Left lower first primary molar tooth',
                    'Iso designation 52', 'I element', 'A mouse', 'Upper case roman letter v (qualifier value)', 'Stage level 1 (qualifier value)', 
                    'Ampere (a)', 'Universal designation 1d', 'Deci', 'Universal designation l', 'Lower case roman letter l', 
                    'Roman numeral v (qualifier value)', 'Right upper lateral primary incisor tooth', 'Primary upper right b tooth', 
                    'Blood group antigen v (substance)', 'Vol', 'Blood group antigen hr<sup>v</sup>', "Rexed's lamina i", 
                    'Spongiosas, zona', 'Lamina i of gray matter of spinal cord', 'Right upper second deciduous molar tooth', 
                    'Acre (qualifier value)', 'Annum', 'A antigen', 'Lymphoma staging symptom status a', 'Rh(d)antigen polypeptide',
                    'Cortex, visual', 'Iodine, nos', 'L-', 'Lamina v', 'Iodine', 'I antigen', 'Rho(d) antigen', 'Litre',
                    'Tumor staging descriptor d', 'Visual areas', 'Days', 'Deciduous maxillary left first molar tooth', 
                    'Haderup designation +04', 'Lower case roman letter l (qualifier value)', 'Da', 'Posteromarginal nucleus',],
       
        "parent": ['Dentitions, deciduous', 'Baby tooth', 'Milk tooth', 'Dentition primary', 'Set of deciduous teeth', 
                   'Primary molar tooth', 'Upper jaw region structure', 'Deciduous dentition', 'Teeth, primary', 
                   'Primary upper right molar tooth (body structure)', 'Right upper second permanent molar tooth', 
                   'Entire deciduous molar tooth (body structure)', 'Primary teeth', 'Teeth, deciduous', 'Tooth, milk',
                   '2', 'Entire permanent tooth', 'Deciduous teeth', 'Teeth, baby', 'Temporary molar tooth', 'Primary dentition',
                   'Teeth, milk', 'Structure of deciduous tooth', 'Tooth, deciduous', 'Structure of primary upper tooth (body structure)', 
                   'Entire deciduous molar tooth', 'Haderup designation 7+', 'Set of primary teeth', 'Upper jaw region structure (body structure)',
                   'Dentition, primary', 'Tooth 2', 'All deciduous teeth (body structure)', 'Primary tooth', 'All deciduous teeth', 
                   'Structure of deciduous molar tooth (body structure)', 'Milk teeth', 'Tooth, primary', 'All deciduous teeth, nos', 
                   'Permanent upper right second molar tooth', 'Deciduous molar tooth', 'All teeth, gums and supporting structures (body structure)', 
                   'All teeth, gums and supporting structures', 'Entire primary upper right molar tooth (body structure)', 'Jaw upper', 
                   'Baby teeth', 'Iso designation 17', 'Right upper second secondary molar tooth', 'Structure of deciduous molar tooth', 
                   'Dentes decidui', 'Structure of maxillary right second molar tooth', 'Entire primary upper right molar tooth', 'Temporary tooth',
                   'Maxillary right second molar tooth', 'Right maxillary second molar tooth', 'Permanent tooth', 'Permanent upper right 7 tooth', 
                   'Deciduous tooth', 'Deciduous dentitions', 'Upper jaw region', 'Primary dentitions', 'Upper jaw', 'Right maxillary second secondary molar tooth', 
                   'Dentitions, primary', 'Secondary tooth 2', 'Tooth, baby', 'Deciduous tooth, nos', 'Structure of deciduous tooth (body structure)', 'Upper second primary molar tooth', 
                   'Primary upper rt molar tooth', 'Structure of primary upper tooth', 'Upper jaw region (body structure)', 'Deciduous molar tooth, nos', 
                   '546-548 deciduous teeth', 'Structure of maxillary right second molar tooth (body structure)', 'Entire permanent tooth (body structure)',
                   'Primary upper right molar tooth', 'Dentition, deciduous', 'Ur7 - permanent upper right 7 tooth', 'Universal designation 2', 'Upper second deciduous molar tooth', 
                   'Right upper second molar tooth', 'Upper primary tooth e'],
       
        "child": ['55 - primary upper right second molar tooth', 'Antibody a', 'Am ag', 'Blood group a<sub>x</sub>', 'A1 immunologic symbol', 
                'Iso designation 55', 'A ab', 'A', 'Haderup designation 05+', 'Ax', 'Blood group antigen a', 'A3 ag',
                 'Am', 'Universal designation a', 'Abo1 (isbt symbol)', 'Entire deciduous maxillary right second molar tooth (body structure)',
                'Primary upper rt second molar', 'A3 antigen', 'A antigen', '55 - primary uppr rt 2nd molar', 'A1', 'Blood group a>x<', 
                'A ag &#x7c; donor &#x7c; red blood cells', 'Ure - primary upper right e tooth', 'Primary upper right e tooth', 
                'Am antigen', 'A ag', 'A ag &#x7c; red blood cells', 'A ag &#x7c; blood product unit &#x7c; red blood cells',
                'Blood group antigen a, nos', 'Blood group antigen a (substance)', 'Group ax', 'Blood group a>x< (finding)', 
                'Blood group a x (finding)', 'Blood group a<sub>x</sub> (finding)', 'Entire deciduous maxillary right second molar tooth',
                'Primary upper right second molar tooth', 'A antibody', 'Blood group ax', 'Blood group a x', 'Ure - primary upper rt e tooth', 
                'Universal designation 1d'],
       
        "ae": ["Upset stomach", "nausea", "vomiting", "headache", "diarrhea", "constipation", "dizziness"],
        "docs": ["doc1"],
        "type": "drug"
    },


    {
        "term": "abdominal ache",


        "synonym": ['Blood group antigen m, nos', 'M antigen', 'H', 'Tooth c', 'D - day',
                    'Deciduous mandibular left first molar tooth', 'Meals', '[cal]',
                    'Primary upper right central incisor tooth', 'Universal designation 15d', 'Universal designation h',
                    'Right upper second primary molar tooth', 'Centi', 'Antigen c', 'Years',
                    'Cocaine (schedule i substance)', 'L (qualifier value)', 'Henry (qualifier value)',
                    'B (qualifier value)', 'Universal designation l', 'Nano-', 'D ag',
                    ],


        "parent": [ 'Abdominal lymph node tumour invasion status', 'Upper case roman letters', 'Teeth, baby',
                    'Abo h blood groups', 'Deciduous molar tooth', 'Abo blood group system (qualifier value)', 
                    'Blood group antigen a (substance)', 'Base si unit', 'Dentes decidui', 'Inbred mouse strains',
                    'Abo group', 'Baby teeth', 'All teeth, gums and supporting structures (body structure)', 'Strains, inbred mouse',
                    'Abd lymph node tumour inv stat', 'Tooth, milk', 'Blood group antigen', 'Abo blood-group system', 
                    'Unit of time (qualifier value)', 'Blood group antigens [chemical/ingredient]', 'Blood groups, h', 
                    'Abo groups', 'Abo1 (isbt symbol)', 'Deciduous molar tooth, nos', 'H blood group system', 'Abdominal lymph node tumor invasion status',
                    'Abo grouping', 'Abo(h) blood groups', 'Time unit', 'Permanent upper right second molar tooth', 'Blood group antigens',
                    'Non-international system of units unit of area (qualifier value)', 'Lymphoma staging symptom status values (tumor staging)', 
                    'Deciduous tooth, nos', 'Structure of deciduous tooth', 'A', 'Set of primary teeth', 'Inbred strains of mice',
                    'Milk tooth', 'Maxillary right second molar tooth', 'Right maxillary second molar tooth', 'Primary upper right molar tooth', 
                    'Dentitions, primary', 'Non-international system of units unit of time', 'Abo blood-group systems', 'Deciduous tooth', 
                    'Unit of length (qualifier value)', 'Blood-group systems, abo', 'Electric current unit', 'Structure of primary upper tooth', 
                    'Abo blood-group system [chemical/ingredient]', 'System, abo blood-group', 'Right maxillary second secondary molar tooth', 
                    'Add tumor staging descriptors', 'All deciduous teeth', 'Upper second primary molar tooth', 'Permanent upper right 7 tooth', 'Non-si unit of length (qualifier value)', 
                    'Unit of area', 'Ageu', 'Secondary tooth 2', 'Area unit', 'Entire deciduous molar tooth', 'H blood group', 
                    'Blood group abo', 'Lower case roman letters (qualifier value)', 'Structure of primary upper tooth (body structure)', 'Blood group, abh', 
                    'Entire permanent tooth (body structure)', 'Mouse inbred strains', 'Blood group antigen a', 'Abo blood group antigen system', 'Universal designation 2', 
                    'Right upper second molar tooth', 'Blood group antigen (substance)', 'Abd lymph node tumor inv stat', 'A antigen', 'H blood groups', 'D11-d12 abo blood group antigens',
                    'Dentition, deciduous', 'Ur7 - permanent upper right 7 tooth', 'Teeth, primary', 'Upper jaw', 'Calendarcycletwoletter', 'Baby tooth', 'Retroperitoneal lymph node tumour invasion status',
                    'Upper second deciduous molar tooth', 'Additional tumor staging descriptor (tumor staging)',
                    'Non-si unit of time', 'Tooth, deciduous', 'Mouse strains, inbred', 'Antigens blood group', 
                    'Primary dentitions', 'Haderup designation 7+', 'Structure of maxillary right second molar tooth', 
                    'Metric prefix', 'Blood group antigen, nos', 'Upper jaw region (body structure)', 'Upper primary tooth e', 
                    'Teeth, milk', 'Entire primary upper right molar tooth', 'Structure of maxillary right second molar tooth (body structure)', 
                     'Non-international system of units unit of length (qualifier value)', 'Milk teeth', 'Non-international system of units unit of length',
                    'Dentitions, deciduous', 'Non-si unit of length', 'Teeth, deciduous', 'Entire deciduous molar tooth (body structure)',
                    'Antigen in abo blood group system (substance)', 'Structure of deciduous tooth (body structure)', 
                    'Lower case roman letter', 'Strain, inbred mouse', 'Add tumour staging descriptors', 'Unitofmeasureatomsens',
                    'Inbred strain of mouse', 'Mouse strain, inbred', 'Non-international system of units unit of time (qualifier value)', 
                    'Tooth 2', 'Additional tumor staging descriptors', 'Lower case roman letter (qualifier value)', 'Abo system', 
                    'Primary upper right molar tooth (body structure)', 'Abo blood group, nos', 'Additional tumor staging descriptors (tumor staging)',
                     'Upper jaw region', 'Systems, abo blood-group', 'Primary upper rt molar tooth', 'Unitofmeasureatominsens', 
                     'Blood groups--abo system', 'Primary molar tooth', 'Mouse, inbred strain', 'Deciduous teeth', 'Retroperitoneal lymph node tumor invasion status',
                    'Jaw upper', 'Upper jaw region structure', 'Abo blood group antigens', 'Blood-group system, abo', 
                    'Mouse inbred strain', 'Unit of age', 'Right upper second permanent molar tooth'],
       
        "child": ['Iso designation 55', '55 - primary uppr rt 2nd molar', 'Haderup designation 05+', 
                  'Entire deciduous maxillary right second molar tooth (body structure)', 'A ag &#x7c; red blood cells', 
                  'Universal designation 1d', '55 - primary upper right second molar tooth', 'Primary upper rt second molar', 
                  'Universal designation a', 'Primary upper right e tooth', 'Ure - primary upper rt e tooth', 'Ure - primary upper right e tooth', 
                  'Entire deciduous maxillary right second molar tooth', 'Primary upper right second molar tooth'],
        "ae": [],
        "docs": ["doc1", "doc2", "doc1"],
        "type": "event"
    }
]